apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flink.fullname" . }}
  labels:
    app: flink
    app.kubernetes.io/name: {{ include "flink.name" . }}
    helm.sh/chart: {{ include "flink.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: {{ include "flink.fullname" . }}-jobmanager
    taskmanager.numberOfTaskSlots: {{ .Values.taskManager.numberOfTaskSlots }}
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    jobmanager.heap.size: {{ .Values.jobManager.heapSize }}
    taskmanager.heap.size: {{ .Values.taskManager.heapSize }}
  log4j.properties: |+
{{ .Values.log4jProperties | indent 4 }}

