apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flink.fullname" . }}
  labels:
    app: flink
    app.kubernetes.io/name: {{ include "flink.name" . }}
    helm.sh/chart: {{ include "flink.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  flink-conf.yaml: {{ .Values.flinkConf }}
  log4j.properties: {{ .Values.log4jProperties }}

