apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "flink.fullname" . }}-jobmanager
  labels:
    app: flink
    component: jobmanager
    app.kubernetes.io/name: {{ include "flink.name" . }}-jobmanager
    helm.sh/chart: {{ include "flink.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flink.name" . }}-jobmanager
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flink.name" . }}-jobmanager
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: flink-config-volume
          configMap:
            name: {{ include "flink.fullname" . }}
            items:
              - key: flink-conf.yaml
                path: flink-conf.yaml
              - key: log4j.properties
                path: log4j.properties
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /opt/flink
          command: ["/bin/bash", "-c", "$FLINK_HOME/bin/jobmanager.sh start;\
            while :;
            do
              if [[ -f $(find log -name '*jobmanager*.log' -print -quit) ]];
                then tail -f -n +1 log/*jobmanager*.log;
              fi;
            done"]
          ports:
            - containerPort: 6123
              name: rpc
              protocol: TCP
            - containerPort: 6124
              name: blob
              protocol: TCP
            - containerPort: 8081
              name: ui
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6123
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            tcpSocket:
              port: 6123
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
          - name: flink-config-volume
            mountPath: /opt/flink/conf
          resources:
{{ toYaml .Values.jobManager.resources | indent 12 }}
    {{- with .Values.jobManager.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.jobManager.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.jobManager.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
