{{- if .Values.taskManager.hpa.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "flink.fullname" . }}-taskmanager
  labels:
    app: flink
    component: taskmanager
    app.kubernetes.io/name: {{ include "flink.name" . }}-taskmanager
    helm.sh/chart: {{ include "flink.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: {{ include "flink.fullname" . }}-taskmanager
  minReplicas: {{ .Values.taskManager.hpa.minReplicas }}
  maxReplicas: {{ .Values.taskManager.hpa.maxReplicas }}
  metrics:
  {{- if .Values.taskManager.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.taskManager.hpa.memory }}
  {{- end }}
  {{- if .Values.taskManager.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.taskManager.hpa.cpu }}
  {{- end }}
  {{- if .Values.taskManager.hpa.requests }}
  - type: Pod
      pods:
        metricName: http_requests
        targetAverageValue: {{ .Values.taskManager.hpa.requests }}
  {{- end }}
{{- end }}