{{- $fullName := include "flink.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-jobmanager
  labels:
    app.kubernetes.io/name: {{ include "flink.name" . }}
    helm.sh/chart: {{ include "flink.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.jobManager.service.type }}
  ports:
    - name: rpc
      protocol: TCP
      port: 6123
    - name: blob
      protocol: TCP
      port: 6124
    - name: ui
      protocol: TCP
      port: 8081
  selector:
    app: flink
    component: jobmanager
    app.kubernetes.io/name: {{ include "flink.name" . }}-jobmanager
    helm.sh/chart: {{ include "flink.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
